---
title: Jsc Ben.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: JSCBen
description: Data Visualizer
avatar: https://avatars2.githubusercontent.com/u/34761601?s=460&v=4
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: JSCBen
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: BenTwist14
  stackoverflow: 
  youtube: 
  googleplus: 
disqus:
  shortname: BenTwist
google_analytics: 
url: 
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
theme: minima
